"""Add date_from and date_to to shared_dashboards

Revision ID: 4164acc6c47b
Revises: bcbd0320fcb0
Create Date: 2026-03-09 18:52:37.413395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4164acc6c47b'
down_revision = 'bcbd0320fcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_dashboards', schema=None) as batch_op:
        batch_op.drop_column('date_to')
        batch_op.drop_column('date_from')

    # ### end Alembic commands ###
