"""Add signup_source to accounts for acquisition tracking

Revision ID: 99ce1a65ff86
Revises: 4164acc6c47b
Create Date: 2026-03-09 20:42:47.896464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ce1a65ff86'
down_revision = '4164acc6c47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_source', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('signup_source')

    # ### end Alembic commands ###
