"""add founding member fields and update free tier to 50

Revision ID: f8c7c523af15
Revises: 99ce1a65ff86
Create Date: 2026-03-13 21:10:10.736745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c7c523af15'
down_revision = '99ce1a65ff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_founding_member', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('founding_member_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('founding_member_number')
        batch_op.drop_column('is_founding_member')

    # ### end Alembic commands ###
